<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('food')->insert(

            [
                [
                    "id" => 1,
                    "typeId" => 1,
                    "EnName" => "Apple",
                    "ArName" => "تفاح",
                    "image" => "foods/food1.jpg",
                    "kcal" => 52,
                    "protein" => 0.3,
                    "carbs" => 13.8,
                    "fats" => 0.2,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 2,
                    "typeId" => 1,
                    "EnName" => "Banana",
                    "ArName" => "موز",
                    "image" => "foods/food2.jpg",
                    "kcal" => 89,
                    "protein" => 1.1,
                    "carbs" => 22.8,
                    "fats" => 0.3,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 3,
                    "typeId" => 2,
                    "EnName" => "Potato",
                    "ArName" => "بطاطس",
                    "image" => "foods/food3.jpg",
                    "kcal" => 77,
                    "protein" => 2,
                    "carbs" => 17.6,
                    "fats" => 0.1,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 4,
                    "typeId" => 2,
                    "EnName" => "Tomato",
                    "ArName" => "طماطم",
                    "image" => "foods/food4.jpg",
                    "kcal" => 18,
                    "protein" => 0.9,
                    "carbs" => 3.9,
                    "fats" => 0.2,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 5,
                    "typeId" => 2,
                    "EnName" => "Onion",
                    "ArName" => "بصل",
                    "image" => "foods/food5.jpg",
                    "kcal" => 40,
                    "protein" => 1.1,
                    "carbs" => 9.3,
                    "fats" => 0.1,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 6,
                    "typeId" => 2,
                    "EnName" => "Garlic",
                    "ArName" => "ثوم",
                    "image" => "foods/food6.jpg",
                    "kcal" => 149,
                    "protein" => 6.4,
                    "carbs" => 33.1,
                    "fats" => 0.5,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 7,
                    "typeId" => 2,
                    "EnName" => "Pepper",
                    "ArName" => "فلفل",
                    "image" => "foods/food7.jpg",
                    "kcal" => 20,
                    "protein" => 0.9,
                    "carbs" => 4.7,
                    "fats" => 0.2,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 8,
                    "typeId" => 3,
                    "EnName" => "lentils",
                    "ArName" => "عدس",
                    "image" => "foods/food8.jpg",
                    "kcal" => 353,
                    "protein" => 25,
                    "carbs" => 60,
                    "fats" => 1.1,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 9,
                    "typeId" => 3,
                    "EnName" => "Chickpeas",
                    "ArName" => "حمص",
                    "image" => "foods/food9.jpg",
                    "kcal" => 364,
                    "protein" => 19,
                    "carbs" => 61,
                    "fats" => 6,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 10,
                    "typeId" => 3,
                    "EnName" => "Black Beans",
                    "ArName" => "فاصوليا سوداء",
                    "image" => "foods/food10.jpg",
                    "kcal" => 339,
                    "protein" => 21.6,
                    "carbs" => 62.4,
                    "fats" => 0.9,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 12,
                    "typeId" => 4,
                    "EnName" => "Rice",
                    "ArName" => "أرز",
                    "image" => "foods/food11.jpg",
                    "kcal" => 365,
                    "protein" => 7,
                    "carbs" => 80,
                    "fats" => 0.7,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 13,
                    "typeId" => 4,
                    "EnName" => "oats",
                    "ArName" => "شوفان",
                    "image" => "foods/food12.jpg",
                    "kcal" => 368,
                    "protein" => 14.1,
                    "carbs" => 64,
                    "fats" => 6.1,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 14,
                    "typeId" => 4,
                    "EnName" => "bulgur",
                    "ArName" => "برغل",
                    "image" => "foods/food13.jpg",
                    "kcal" => 342,
                    "protein" => 12.3,
                    "carbs" => 75,
                    "fats" => 13,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 15,
                    "typeId" => 5,
                    "EnName" => "Almonds",
                    "ArName" => "لوز",
                    "image" => "foods/food14.jpg",
                    "kcal" => 579,
                    "protein" => 21.6,
                    "carbs" => 21.6,
                    "fats" => 49.9,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 16,
                    "typeId" => 5,
                    "EnName" => "walnuts",
                    "ArName" => "جوز",
                    "image" => "foods/food15.jpg",
                    "kcal" => 654,
                    "protein" => 15.2,
                    "carbs" => 13.7,
                    "fats" => 65.2,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 17,
                    "typeId" => 5,
                    "EnName" => "cashews",
                    "ArName" => "كاجو",
                    "image" => "foods/food16.jpg",
                    "kcal" => 553,
                    "protein" => 18.2,
                    "carbs" => 30.2,
                    "fats" => 43.8,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 18,
                    "typeId" => 5,
                    "EnName" => "pistachios",
                    "ArName" => "فستق",
                    "image" => "foods/food17.jpg",
                    "kcal" => 562,
                    "protein" => 20.6,
                    "carbs" => 28,
                    "fats" => 45.3,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 19,
                    "typeId" => 6,
                    "EnName" => "Beef",
                    "ArName" => "لحم بقري",
                    "image" => "foods/food18.jpg",
                    "kcal" => 165,
                    "protein" => 31,
                    "carbs" => 0,
                    "fats" => 3.6,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 20,
                    "typeId" => 6,
                    "EnName" => "Lamb",
                    "ArName" => "لحم ضأن",
                    "image" => "foods/food19.jpg",
                    "kcal" => 294,
                    "protein" => 25,
                    "carbs" => 0,
                    "fats" => 21,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 21,
                    "typeId" => 6,
                    "EnName" => "Chicken Breast",
                    "ArName" => "صدر دجاج",
                    "image" => "foods/food20.jpg",
                    "kcal" => 165,
                    "protein" => 31,
                    "carbs" => 0,
                    "fats" => 3.6,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 22,
                    "typeId" => 6,
                    "EnName" => "turkey",
                    "ArName" => "ديك رومي",
                    "image" => "foods/food21.jpg",
                    "kcal" => 135,
                    "protein" => 29,
                    "carbs" => 0,
                    "fats" => 1,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 23,
                    "typeId" => 7,
                    "EnName" => "salmon",
                    "ArName" => "سلمون",
                    "image" => "foods/food22.jpg",
                    "kcal" => 208,
                    "protein" => 20,
                    "carbs" => 0,
                    "fats" => 13,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 24,
                    "typeId" => 7,
                    "EnName" => "tuna",
                    "ArName" => "تونة",
                    "image" => "foods/food23.jpg",
                    "kcal" => 132,
                    "protein" => 28,
                    "carbs" => 0,
                    "fats" => 1,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 25,
                    "typeId" => 7,
                    "EnName" => "trout",
                    "ArName" => "تروتة",
                    "image" => "foods/food24.jpg",
                    "kcal" => 148,
                    "protein" => 19,
                    "carbs" => 0,
                    "fats" => 7,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 26,
                    "typeId" => 7,
                    "EnName" => "mackerel",
                    "ArName" => "ماكريل",
                    "image" => "foods/food25.jpg",
                    "kcal" => 305,
                    "protein" => 20,
                    "carbs" => 0,
                    "fats" => 25,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 27,
                    "typeId" => 8,
                    "EnName" => "milk",
                    "ArName" => "حليب",
                    "image" => "foods/food26.jpg",
                    "kcal" => 42,
                    "protein" => 3.4,
                    "carbs" => 4.8,
                    "fats" => 1,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 28,
                    "typeId" => 8,
                    "EnName" => "yogurt",
                    "ArName" => "زبادي",
                    "image" => "foods/food27.jpg",
                    "kcal" => 59,
                    "protein" => 10,
                    "carbs" => 3.6,
                    "fats" => 0.4,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 29,
                    "typeId" => 8,
                    "EnName" => "cheddar cheese",
                    "ArName" => "جبنة شيدر",
                    "image" => "foods/food28.jpg",
                    "kcal" => 402,
                    "protein" => 25,
                    "carbs" => 1.3,
                    "fats" => 33,
                    "haveExplane" => 0,
                ],
                [
                    "id" => 30,
                    "typeId" => 8,
                    "EnName" => "butter",
                    "ArName" => "زبدة",
                    "image" => "foods/food29.jpg",
                    "kcal" => 717,
                    "protein" => 0.9,
                    "carbs" => 0.1,
                    "fats" => 81,
                    "haveExplane" => 0,
                ]
            ]

        );
    }
}
